// This file is autogenerated by `quarry introspect`. Do not edit manually.

import type { ClickHouseDateTime, ClickHouseUInt64, Generated, TypedTable } from "quarry";

export interface Events {
  tenant_id: number;
  user_id: ClickHouseUInt64;
  event_type: string;
  created_at: ClickHouseDateTime;
  duration_ms: Generated<number>;
}

export interface Tables {
  events: TypedTable<Events>;
}

export interface Views {}

export interface DB extends Tables, Views {}
