import { describe, expect, it } from "vitest";
import {
  buildSchemaModule,
  buildSchemaModuleResult,
  filterExcludedObjects,
  formatIntrospectionFailureReport,
  formatIntrospectionSummaryReport,
  resolveConnectionOptions,
} from "../src/introspect";

describe("CLI introspection helpers", () => {
  it("uses include and exclude patterns from command args", () => {
    expect(
      resolveConnectionOptions(
        {
          url: "http://localhost:8123",
          database: "analytics",
          includePattern: "^public_",
          excludePattern: "^public_tmp_",
        },
        {
          CLICKHOUSE_URL: "http://env-host:8123",
          CLICKHOUSE_DATABASE: "default",
          CLICKHOUSE_USER: "env-user",
        },
      ),
    ).toEqual({
      url: "http://localhost:8123",
      user: "env-user",
      password: undefined,
      database: "analytics",
      includePattern: /^public_/,
      excludePattern: /^public_tmp_/,
    });
  });

  it("validates include and exclude patterns", () => {
    expect(() =>
      resolveConnectionOptions({ url: "http://localhost:8123", includePattern: "(" }, {}),
    ).toThrow("Invalid includePattern '(':");

    expect(() =>
      resolveConnectionOptions({ url: "http://localhost:8123", excludePattern: "(" }, {}),
    ).toThrow("Invalid excludePattern '(':");
  });

  it("requires a ClickHouse URL from args or env", () => {
    expect(() => resolveConnectionOptions({}, {})).toThrow(
      "Missing ClickHouse URL. Pass --url or set CLICKHOUSE_URL in the environment.",
    );
  });

  it("can restrict introspection input to table-like objects", () => {
    expect(
      buildSchemaModule([
        {
          name: "users",
          engine: "MergeTree",
          createTableQuery: `
            CREATE TABLE default.users (
              id UInt32
            )
            ENGINE = MergeTree
            ORDER BY id
          `,
        },
      ]),
    ).toContain("table.mergeTree");
  });

  it("adds an autogenerated header with safe generation options", () => {
    const source = buildSchemaModule(
      [
        {
          name: "users",
          engine: "MergeTree",
          createTableQuery: `
            CREATE TABLE default.users (
              id UInt32
            )
            ENGINE = MergeTree
            ORDER BY id
          `,
        },
      ],
      {
        database: "analytics",
        tablesOnly: true,
        includePattern: "^public_",
        excludePattern: "^public_tmp_",
      },
    );

    expect(source.startsWith("// This file is autogenerated by `quarry introspect`.")).toBe(true);
    expect(source).toContain('// - database: "analytics"');
    expect(source).toContain("// - tablesOnly: true");
    expect(source).toContain('// - includePattern: "^public_"');
    expect(source).toContain('// - excludePattern: "^public_tmp_"');
    expect(source).toContain(
      'import { defineSchema, table, type SchemaBuilder, UInt32 } from "@oorestisime/quarry";',
    );
  });

  it("returns supported output and reports unsupported objects separately", () => {
    const result = buildSchemaModuleResult([
      {
        name: "users",
        engine: "MergeTree",
        createTableQuery: `
          CREATE TABLE default.users (
            id UInt32
          )
          ENGINE = MergeTree
          ORDER BY id
        `,
      },
      {
        name: "user_events",
        engine: "SharedMergeTree",
        createTableQuery: `
          CREATE TABLE default.user_events (
            id UInt32
          )
          ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
          ORDER BY id
          SAMPLE BY id
        `,
      },
    ]);

    expect(result.source).toContain("users: table.mergeTree");
    expect(result.failures).toEqual([
      {
        name: "user_events",
        engine: "SharedMergeTree",
        message: "Unsupported table clause 'SAMPLE BY' in table 'user_events'.",
      },
    ]);
    expect(result.summary).toEqual({
      generatedObjects: 1,
      generatedTables: 1,
      generatedViews: 0,
      skippedObjects: 1,
    });
    expect(formatIntrospectionSummaryReport(result.summary)).toBe(
      "Generated 1 object: 1 table, 0 views. Skipped 1 object.",
    );
    expect(formatIntrospectionFailureReport(result.failures)).toContain(
      "Skipped 1 unsupported objects:",
    );
  });

  it("skips views whose referenced sources were not generated", () => {
    const result = buildSchemaModuleResult([
      {
        name: "mv_signup_channel_attribution",
        engine: "View",
        createTableQuery: `
          CREATE VIEW default.mv_signup_channel_attribution AS
          SELECT *
          FROM default.missing_source FINAL
          WHERE is_deleted = 0
        `,
      },
      {
        name: "users",
        engine: "MergeTree",
        createTableQuery: `
          CREATE TABLE default.users (
            id UInt32
          )
          ENGINE = MergeTree
          ORDER BY id
        `,
      },
      {
        name: "final_student_attribution",
        engine: "View",
        createTableQuery: `
          CREATE VIEW default.final_student_attribution AS
          SELECT *
          FROM default.mv_signup_channel_attribution FINAL
        `,
      },
    ]);

    expect(result.source).toContain("users: table.mergeTree");
    expect(result.source).not.toContain("final_student_attribution");
    expect(result.failures).toContainEqual({
      name: "mv_signup_channel_attribution",
      engine: "View",
      message: "Referenced source 'missing_source' was not generated.",
    });
    expect(result.failures).toContainEqual({
      name: "final_student_attribution",
      engine: "View",
      message: "Referenced source 'mv_signup_channel_attribution' was not generated.",
    });
    expect(result.summary).toEqual({
      generatedObjects: 1,
      generatedTables: 1,
      generatedViews: 0,
      skippedObjects: 2,
    });
  });

  it("preserves default clauses while building the schema module", () => {
    expect(
      buildSchemaModule([
        {
          name: "users",
          engine: "MergeTree",
          createTableQuery: `
            CREATE TABLE default.users (
              id UInt32,
              created_at DateTime64(3) DEFAULT now64(3)
            )
            ENGINE = MergeTree
            ORDER BY id
          `,
        },
      ]),
    ).toContain('created_at: DateTime64(3).defaultSql("now64(3)")');
  });

  it("filters object names through include and exclude patterns", () => {
    expect(
      filterExcludedObjects(
        [
          {
            name: "_peerdb_raw_mirror_7b15851c__04a4__4279__83c7__16a491c86c75",
            engine: "SharedMergeTree",
            createTableQuery:
              "CREATE TABLE default._peerdb_raw_mirror_7b15851c__04a4__4279__83c7__16a491c86c75 (id UInt32) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}') ORDER BY id",
          },
          {
            name: "public_users",
            engine: "SharedReplacingMergeTree",
            createTableQuery:
              "CREATE TABLE default.public_users (id UInt32) ENGINE = SharedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}', id) ORDER BY id",
          },
          {
            name: "public_tmp_users",
            engine: "SharedReplacingMergeTree",
            createTableQuery:
              "CREATE TABLE default.public_tmp_users (id UInt32) ENGINE = SharedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}', id) ORDER BY id",
          },
        ],
        /^public_/,
        /^public_tmp_/,
      ),
    ).toEqual([
      {
        name: "public_users",
        engine: "SharedReplacingMergeTree",
        createTableQuery:
          "CREATE TABLE default.public_users (id UInt32) ENGINE = SharedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}', id) ORDER BY id",
      },
    ]);
  });

  it("fails fast with object-specific errors for unsupported DDL", () => {
    expect(() =>
      buildSchemaModule([
        {
          name: "users",
          engine: "MergeTree",
          createTableQuery: `
            CREATE TABLE default.users (
              id UInt32,
              created_at DateTime64(3)
            )
            ENGINE = MergeTree
            ORDER BY id
            SAMPLE BY id
          `,
        },
      ]),
    ).toThrow("- users (MergeTree): Unsupported table clause 'SAMPLE BY' in table 'users'.");
  });
});
