import { describe, expect, it } from "vitest";
import {
  buildTypeScriptModuleResult,
  filterExcludedObjects,
  formatIntrospectionFailureReport,
  formatIntrospectionSummaryReport,
  resolveConnectionOptions,
} from "../src/introspect";

describe("CLI introspection helpers", () => {
  it("uses include and exclude patterns from command args", () => {
    expect(
      resolveConnectionOptions(
        {
          url: "http://localhost:8123",
          database: "analytics",
          includePattern: "^public_",
          excludePattern: "^public_tmp_",
        },
        {
          CLICKHOUSE_URL: "http://env-host:8123",
          CLICKHOUSE_DATABASE: "default",
          CLICKHOUSE_USER: "env-user",
        },
      ),
    ).toEqual({
      url: "http://localhost:8123",
      user: "env-user",
      password: undefined,
      database: "analytics",
      includePattern: /^public_/,
      excludePattern: /^public_tmp_/,
    });
  });

  it("validates include and exclude patterns", () => {
    expect(() =>
      resolveConnectionOptions({ url: "http://localhost:8123", includePattern: "(" }, {}),
    ).toThrow("Invalid includePattern '(':");

    expect(() =>
      resolveConnectionOptions({ url: "http://localhost:8123", excludePattern: "(" }, {}),
    ).toThrow("Invalid excludePattern '(':");
  });

  it("requires a ClickHouse URL from args or env", () => {
    expect(() => resolveConnectionOptions({}, {})).toThrow(
      "Missing ClickHouse URL. Pass --url or set CLICKHOUSE_URL in the environment.",
    );
  });

  it("filters object names through include and exclude patterns", () => {
    expect(
      filterExcludedObjects(
        [
          {
            name: "_peerdb_raw_mirror_7b15851c__04a4__4279__83c7__16a491c86c75",
            engine: "SharedMergeTree",
          },
          {
            name: "public_users",
            engine: "SharedReplacingMergeTree",
          },
          {
            name: "public_tmp_users",
            engine: "SharedReplacingMergeTree",
          },
        ],
        /^public_/,
        /^public_tmp_/,
      ),
    ).toEqual([
      {
        name: "public_users",
        engine: "SharedReplacingMergeTree",
      },
    ]);
  });

  it("builds named row interfaces with typed source wrappers and ClickHouse aliases", () => {
    const result = buildTypeScriptModuleResult(
      [
        {
          name: "users",
          engine: "MergeTree",
        },
        {
          name: "daily_users",
          engine: "View",
        },
        {
          name: "ai.applicationFeature",
          engine: "View",
        },
        {
          name: "28DaysOfBlackHistoryLogs",
          engine: "MergeTree",
        },
      ],
      [
        { objectName: "users", name: "id", clickhouseType: "UInt32", position: 1 },
        { objectName: "users", name: "created_at", clickhouseType: "DateTime64(3)", position: 2 },
        { objectName: "users", name: "big_user_id", clickhouseType: "UInt64", position: 3 },
        {
          objectName: "users",
          name: "location",
          clickhouseType: "Tuple(Float64, Float64)",
          position: 4,
        },
        {
          objectName: "users",
          name: "attributes",
          clickhouseType: "Map(String, String)",
          position: 5,
        },
        {
          objectName: "users",
          name: "history",
          clickhouseType: "Array(DateTime64(3))",
          position: 6,
        },
        {
          objectName: "users",
          name: "maybe_created",
          clickhouseType: "Nullable(DateTime64(3))",
          position: 7,
        },
        { objectName: "users", name: "payload", clickhouseType: "Object('json')", position: 8 },
        { objectName: "daily_users", name: "signup_date", clickhouseType: "Date", position: 1 },
        { objectName: "daily_users", name: "total_users", clickhouseType: "UInt64", position: 2 },
        {
          objectName: "ai.applicationFeature",
          name: "feature_name",
          clickhouseType: "String",
          position: 1,
        },
        {
          objectName: "28DaysOfBlackHistoryLogs",
          name: "created_at",
          clickhouseType: "DateTime",
          position: 1,
        },
      ],
      {
        database: "analytics",
        tablesOnly: false,
        includePattern: "^public_",
      },
    );

    expect(result.source.startsWith("// This file is autogenerated by `quarry introspect`.")).toBe(
      true,
    );
    expect(result.source).toContain('// - database: "analytics"');
    expect(result.source).toContain("// - tablesOnly: false");
    expect(result.source).toContain('// - includePattern: "^public_"');
    expect(result.source).toContain("import type {");
    expect(result.source).toContain('} from "@oorestisime/quarry";');
    expect(result.source).toContain("ClickHouseDateTime64");
    expect(result.source).toContain("ClickHouseUInt64");
    expect(result.source).toContain("TypedTable");
    expect(result.source).toContain("TypedView");
    expect(result.source).toContain("export interface Users {");
    expect(result.source).toContain("export interface DailyUsers {");
    expect(result.source).toContain("export interface AiApplicationFeature {");
    expect(result.source).toContain("export interface _28DaysOfBlackHistoryLogs {");
    expect(result.source).toContain("export interface Tables");
    expect(result.source).toContain("export interface Views");
    expect(result.source).toContain("export interface DB extends Tables, Views {}");
    expect(result.source).toContain("users: TypedTable<Users>;");
    expect(result.source).toContain(
      '"28DaysOfBlackHistoryLogs": TypedTable<_28DaysOfBlackHistoryLogs>;',
    );
    expect(result.source).toContain('"ai.applicationFeature": TypedView<AiApplicationFeature>;');
    expect(result.source).toContain("daily_users: TypedView<DailyUsers>;");
    expect(result.source).toContain("id: number;");
    expect(result.source).toContain("created_at: ClickHouseDateTime64;");
    expect(result.source).toContain("big_user_id: ClickHouseUInt64;");
    expect(result.source).toContain("location: [number, number];");
    expect(result.source).toContain("attributes: Record<string, string>;");
    expect(result.source).toContain("history: Array<string>;");
    expect(result.source).toContain("maybe_created: ClickHouseDateTime64 | null;");
    expect(result.source).toContain("payload: unknown;");
    expect(result.source).toContain("signup_date: ClickHouseDate;");
    expect(result.source).toContain("total_users: ClickHouseUInt64;");
    expect(result.summary).toEqual({
      generatedObjects: 4,
      generatedTables: 2,
      generatedViews: 2,
      skippedObjects: 0,
    });
  });

  it("skips objects whose column metadata is missing", () => {
    const result = buildTypeScriptModuleResult(
      [
        {
          name: "users",
          engine: "MergeTree",
        },
        {
          name: "daily_users",
          engine: "View",
        },
      ],
      [{ objectName: "users", name: "id", clickhouseType: "UInt32", position: 1 }],
    );

    expect(result.source).toContain("export interface Tables");
    expect(result.source).not.toContain("daily_users");
    expect(result.failures).toEqual([
      {
        name: "daily_users",
        engine: "View",
        message: "Could not load column metadata for the introspected object.",
      },
    ]);
    expect(formatIntrospectionSummaryReport(result.summary)).toBe(
      "Generated 1 object: 1 table, 0 views. Skipped 1 object.",
    );
    expect(formatIntrospectionFailureReport(result.failures)).toContain(
      "Skipped 1 unsupported objects:",
    );
  });
});
