import { execFileSync } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import process from "node:process";
import { createClient } from "@clickhouse/client";
import { describeDDLObjects, generateSchemaModuleFromDDL } from "./introspection/index";

export interface IntrospectArgs {
  readonly url?: string;
  readonly user?: string;
  readonly password?: string;
  readonly database?: string;
  readonly out?: string;
  readonly tablesOnly?: boolean;
  readonly includePattern?: string;
  readonly excludePattern?: string;
}

export interface IntrospectionConnectionOptions {
  readonly url: string;
  readonly user?: string;
  readonly password?: string;
  readonly database: string;
  readonly includePattern?: RegExp;
  readonly excludePattern?: RegExp;
}

export interface IntrospectionObject {
  readonly name: string;
  readonly engine: string;
  readonly createTableQuery: string;
}

export interface IntrospectionFailure {
  readonly name: string;
  readonly engine: string;
  readonly message: string;
}

export interface IntrospectionResult {
  readonly source: string;
  readonly failures: readonly IntrospectionFailure[];
  readonly summary: IntrospectionSummary;
}

export interface IntrospectionSummary {
  readonly generatedObjects: number;
  readonly generatedTables: number;
  readonly generatedViews: number;
  readonly skippedObjects: number;
}

export interface IntrospectionSchemaHeaderOptions {
  readonly database?: string;
  readonly tablesOnly?: boolean;
  readonly includePattern?: string;
  readonly excludePattern?: string;
}

interface SystemTableRow {
  readonly name: string;
  readonly engine: string;
  readonly create_table_query: string;
}

const MAX_FAILURE_DETAILS = 40;

function getErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function normalizeCreateStatement(statement: string): string {
  const trimmed = statement.trim();
  return trimmed.endsWith(";") ? trimmed : `${trimmed};`;
}

function sortObjects(left: IntrospectionObject, right: IntrospectionObject): number {
  const leftRank = left.engine.endsWith("View") ? 1 : 0;
  const rightRank = right.engine.endsWith("View") ? 1 : 0;

  if (leftRank !== rightRank) {
    return leftRank - rightRank;
  }

  return left.name.localeCompare(right.name);
}

function tryFormatTypeScript(source: string): string {
  try {
    return execFileSync("oxfmt", ["--stdin-filepath", "schema.ts"], {
      input: source,
      encoding: "utf8",
    });
  } catch {
    return source;
  }
}

function isTableLikeObject(object: IntrospectionObject): boolean {
  return object.engine !== "View";
}

function formatSchemaHeaderValue(value: string | boolean): string {
  return typeof value === "string" ? JSON.stringify(value) : String(value);
}

function pluralize(count: number, singular: string, plural = `${singular}s`): string {
  return `${count} ${count === 1 ? singular : plural}`;
}

function formatSchemaModuleHeader(options: IntrospectionSchemaHeaderOptions = {}): string {
  const entries = [
    ["database", options.database],
    ["tablesOnly", options.tablesOnly],
    ["includePattern", options.includePattern],
    ["excludePattern", options.excludePattern],
  ].filter((entry): entry is [string, string | boolean] => entry[1] !== undefined);

  const lines = ["// This file is autogenerated by `quarry introspect`. Do not edit manually."];

  if (entries.length > 0) {
    lines.push(
      "// Generated with:",
      ...entries.map(([name, value]) => `// - ${name}: ${formatSchemaHeaderValue(value)}`),
    );
  }

  return lines.join("\n");
}

function buildSchemaHeaderOptions(
  args: IntrospectArgs,
  options: Pick<IntrospectionConnectionOptions, "database">,
): IntrospectionSchemaHeaderOptions {
  // Only include non-sensitive options in generated file headers.
  return {
    database: options.database,
    tablesOnly: args.tablesOnly ?? false,
    ...(args.includePattern ? { includePattern: args.includePattern } : {}),
    ...(args.excludePattern ? { excludePattern: args.excludePattern } : {}),
  };
}

export function formatIntrospectionFailureReport(
  failures: readonly IntrospectionFailure[],
  prefix = "Skipped",
): string {
  const visibleFailures = failures.slice(0, MAX_FAILURE_DETAILS);
  const details = visibleFailures
    .map((failure) => `- ${failure.name} (${failure.engine}): ${failure.message}`)
    .join("\n");
  const remainder =
    failures.length > MAX_FAILURE_DETAILS
      ? `\n...and ${failures.length - MAX_FAILURE_DETAILS} more unsupported objects.`
      : "";

  return `${prefix} ${failures.length} unsupported objects:\n${details}${remainder}`;
}

export function formatIntrospectionSummaryReport(summary: IntrospectionSummary): string {
  const report = `Generated ${pluralize(summary.generatedObjects, "object")}: ${pluralize(summary.generatedTables, "table")}, ${pluralize(summary.generatedViews, "view")}.`;
  return summary.skippedObjects > 0
    ? `${report} Skipped ${pluralize(summary.skippedObjects, "object")}.`
    : report;
}

export function resolveConnectionOptions(
  args: IntrospectArgs,
  env: NodeJS.ProcessEnv = process.env,
): IntrospectionConnectionOptions {
  const url = args.url ?? env.CLICKHOUSE_URL;
  if (!url) {
    throw new Error("Missing ClickHouse URL. Pass --url or set CLICKHOUSE_URL in the environment.");
  }

  const compilePattern = (
    pattern: string | undefined,
    name: "includePattern" | "excludePattern",
  ) => {
    if (!pattern) {
      return undefined;
    }

    try {
      return new RegExp(pattern);
    } catch (error) {
      throw new Error(`Invalid ${name} '${pattern}': ${getErrorMessage(error)}`);
    }
  };

  return {
    url,
    user: args.user ?? env.CLICKHOUSE_USER,
    password: args.password ?? env.CLICKHOUSE_PASSWORD,
    database: args.database ?? env.CLICKHOUSE_DATABASE ?? "default",
    ...(args.includePattern
      ? { includePattern: compilePattern(args.includePattern, "includePattern") }
      : {}),
    ...(args.excludePattern
      ? { excludePattern: compilePattern(args.excludePattern, "excludePattern") }
      : {}),
  };
}

export function buildSchemaModule(
  objects: readonly IntrospectionObject[],
  headerOptions?: IntrospectionSchemaHeaderOptions,
): string {
  return buildSchemaModuleResult(objects, headerOptions).source;
}

export function filterExcludedObjects(
  objects: readonly IntrospectionObject[],
  includePattern?: RegExp,
  excludePattern?: RegExp,
): IntrospectionObject[] {
  return objects.filter((object) => {
    if (includePattern && !includePattern.test(object.name)) {
      return false;
    }

    if (excludePattern && excludePattern.test(object.name)) {
      return false;
    }

    return true;
  });
}

export function buildSchemaModuleResult(
  objects: readonly IntrospectionObject[],
  headerOptions?: IntrospectionSchemaHeaderOptions,
): IntrospectionResult {
  if (objects.length === 0) {
    throw new Error("No tables or views were available to introspect.");
  }

  const orderedObjects = [...objects].sort(sortObjects);
  const supportedTables: IntrospectionObject[] = [];
  const candidateViews: Array<IntrospectionObject & { dependencies: readonly string[] }> = [];
  const failures: IntrospectionFailure[] = [];

  for (const object of orderedObjects) {
    try {
      generateSchemaModuleFromDDL(normalizeCreateStatement(object.createTableQuery));

      const [descriptor] = describeDDLObjects(normalizeCreateStatement(object.createTableQuery));
      if (!descriptor) {
        failures.push({
          name: object.name,
          engine: object.engine,
          message: "Could not describe the introspected object.",
        });
        continue;
      }

      if (descriptor.kind === "view") {
        candidateViews.push({
          ...object,
          dependencies: descriptor.dependencies,
        });
      } else {
        supportedTables.push(object);
      }
    } catch (error) {
      failures.push({
        name: object.name,
        engine: object.engine,
        message: getErrorMessage(error),
      });
    }
  }

  const supportedObjects: IntrospectionObject[] = [...supportedTables];
  const resolvedNames = new Set(supportedTables.map((object) => object.name));
  let remainingViews = [...candidateViews];
  let progress = true;

  while (remainingViews.length > 0 && progress) {
    progress = false;
    const nextRemainingViews: typeof remainingViews = [];

    for (const view of remainingViews) {
      if (view.dependencies.every((dependency) => resolvedNames.has(dependency))) {
        supportedObjects.push(view);
        resolvedNames.add(view.name);
        progress = true;
        continue;
      }

      nextRemainingViews.push(view);
    }

    remainingViews = nextRemainingViews;
  }

  for (const view of remainingViews) {
    failures.push({
      name: view.name,
      engine: view.engine,
      message: `Referenced source ${view.dependencies.map((dependency) => `'${dependency}'`).join(", ")} was not generated.`,
    });
  }

  if (supportedObjects.length === 0) {
    if (failures.length > 0) {
      throw new Error(
        formatIntrospectionFailureReport(
          failures,
          "Could not generate a trusted Quarry schema for",
        ),
      );
    }

    throw new Error("No supported tables or views were available to introspect.");
  }

  const ddl = supportedObjects
    .map((object) => normalizeCreateStatement(object.createTableQuery))
    .join("\n\n");

  return {
    source: tryFormatTypeScript(
      `${formatSchemaModuleHeader(headerOptions)}\n\n${generateSchemaModuleFromDDL(ddl)}`,
    ),
    failures,
    summary: {
      generatedObjects: supportedObjects.length,
      generatedTables: supportedTables.length,
      generatedViews: supportedObjects.length - supportedTables.length,
      skippedObjects: failures.length,
    },
  };
}

export async function fetchDatabaseObjects(
  options: IntrospectionConnectionOptions,
  tablesOnly = false,
): Promise<IntrospectionObject[]> {
  const client = createClient({
    url: options.url,
    username: options.user,
    password: options.password,
    request_timeout: 30_000,
  });

  try {
    const result = await client.query({
      query: `
        SELECT
          name,
          engine,
          create_table_query
        FROM system.tables
        WHERE database = {database:String}
          AND engine NOT IN ('Dictionary', 'MaterializedView')
          ${tablesOnly ? "AND engine != 'View'" : ""}
      `,
      query_params: {
        database: options.database,
      },
      format: "JSONEachRow",
    });

    const rows = await result.json<SystemTableRow>();
    return rows.map((row) => ({
      name: row.name,
      engine: row.engine,
      createTableQuery: row.create_table_query,
    }));
  } finally {
    await client.close();
  }
}

export async function writeSchemaModule(source: string, outPath: string): Promise<void> {
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, source, "utf8");
}

export async function introspectDatabase(args: IntrospectArgs): Promise<IntrospectionResult> {
  const options = resolveConnectionOptions(args);
  const allObjects = await fetchDatabaseObjects(options, args.tablesOnly);
  const filteredObjects = filterExcludedObjects(
    allObjects,
    options.includePattern,
    options.excludePattern,
  );
  const objects = args.tablesOnly ? filteredObjects.filter(isTableLikeObject) : filteredObjects;
  if (objects.length === 0) {
    throw new Error(
      args.tablesOnly
        ? `No table-like objects found in database '${options.database}'.`
        : `No tables or views found in database '${options.database}'.`,
    );
  }

  return buildSchemaModuleResult(objects, buildSchemaHeaderOptions(args, options));
}
