import { execFileSync } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import process from "node:process";
import { createClient } from "@clickhouse/client";
import {
  generateTypeScriptSchemaModule,
  type TypeScriptIntrospectionColumn,
} from "./introspection/ts-generator";

export interface IntrospectArgs {
  readonly url?: string;
  readonly user?: string;
  readonly password?: string;
  readonly database?: string;
  readonly out?: string;
  readonly tablesOnly?: boolean;
  readonly includePattern?: string;
  readonly excludePattern?: string;
}

export interface IntrospectionConnectionOptions {
  readonly url: string;
  readonly user?: string;
  readonly password?: string;
  readonly database: string;
  readonly includePattern?: RegExp;
  readonly excludePattern?: RegExp;
}

export interface IntrospectionObject {
  readonly name: string;
  readonly engine: string;
}

export interface IntrospectionFailure {
  readonly name: string;
  readonly engine: string;
  readonly message: string;
}

export interface IntrospectionSummary {
  readonly generatedObjects: number;
  readonly generatedTables: number;
  readonly generatedViews: number;
  readonly skippedObjects: number;
}

export interface IntrospectionResult {
  readonly source: string;
  readonly failures: readonly IntrospectionFailure[];
  readonly summary: IntrospectionSummary;
}

export interface IntrospectionSchemaHeaderOptions {
  readonly database?: string;
  readonly tablesOnly?: boolean;
  readonly includePattern?: string;
  readonly excludePattern?: string;
}

interface SystemTableRow {
  readonly name: string;
  readonly engine: string;
}

interface SystemColumnRow {
  readonly table: string;
  readonly name: string;
  readonly type: string;
  readonly position: number;
}

const MAX_FAILURE_DETAILS = 40;

function getErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function sortObjects(left: IntrospectionObject, right: IntrospectionObject): number {
  const leftRank = left.engine.endsWith("View") ? 1 : 0;
  const rightRank = right.engine.endsWith("View") ? 1 : 0;

  if (leftRank !== rightRank) {
    return leftRank - rightRank;
  }

  return left.name.localeCompare(right.name);
}

function tryFormatTypeScript(source: string): string {
  try {
    return execFileSync("oxfmt", ["--stdin-filepath", "db.ts"], {
      input: source,
      encoding: "utf8",
    });
  } catch {
    return source;
  }
}

function isTableLikeObject(object: IntrospectionObject): boolean {
  return object.engine !== "View";
}

function formatSchemaHeaderValue(value: string | boolean): string {
  return typeof value === "string" ? JSON.stringify(value) : String(value);
}

function pluralize(count: number, singular: string, plural = `${singular}s`): string {
  return `${count} ${count === 1 ? singular : plural}`;
}

function formatSchemaModuleHeader(options: IntrospectionSchemaHeaderOptions = {}): string {
  const entries = [
    ["database", options.database],
    ["tablesOnly", options.tablesOnly],
    ["includePattern", options.includePattern],
    ["excludePattern", options.excludePattern],
  ].filter((entry): entry is [string, string | boolean] => entry[1] !== undefined);

  const lines = ["// This file is autogenerated by `quarry introspect`. Do not edit manually."];

  if (entries.length > 0) {
    lines.push(
      "// Generated with:",
      ...entries.map(([name, value]) => `// - ${name}: ${formatSchemaHeaderValue(value)}`),
    );
  }

  return lines.join("\n");
}

function buildSchemaHeaderOptions(
  args: IntrospectArgs,
  options: Pick<IntrospectionConnectionOptions, "database">,
): IntrospectionSchemaHeaderOptions {
  return {
    database: options.database,
    tablesOnly: args.tablesOnly ?? false,
    ...(args.includePattern ? { includePattern: args.includePattern } : {}),
    ...(args.excludePattern ? { excludePattern: args.excludePattern } : {}),
  };
}

export function formatIntrospectionFailureReport(
  failures: readonly IntrospectionFailure[],
  prefix = "Skipped",
): string {
  const visibleFailures = failures.slice(0, MAX_FAILURE_DETAILS);
  const details = visibleFailures
    .map((failure) => `- ${failure.name} (${failure.engine}): ${failure.message}`)
    .join("\n");
  const remainder =
    failures.length > MAX_FAILURE_DETAILS
      ? `\n...and ${failures.length - MAX_FAILURE_DETAILS} more unsupported objects.`
      : "";

  return `${prefix} ${failures.length} unsupported objects:\n${details}${remainder}`;
}

export function formatIntrospectionSummaryReport(summary: IntrospectionSummary): string {
  const report = `Generated ${pluralize(summary.generatedObjects, "object")}: ${pluralize(summary.generatedTables, "table")}, ${pluralize(summary.generatedViews, "view")}.`;
  return summary.skippedObjects > 0
    ? `${report} Skipped ${pluralize(summary.skippedObjects, "object")}.`
    : report;
}

export function resolveConnectionOptions(
  args: IntrospectArgs,
  env: NodeJS.ProcessEnv = process.env,
): IntrospectionConnectionOptions {
  const url = args.url ?? env.CLICKHOUSE_URL;
  if (!url) {
    throw new Error("Missing ClickHouse URL. Pass --url or set CLICKHOUSE_URL in the environment.");
  }

  const compilePattern = (
    pattern: string | undefined,
    name: "includePattern" | "excludePattern",
  ) => {
    if (!pattern) {
      return undefined;
    }

    try {
      return new RegExp(pattern);
    } catch (error) {
      throw new Error(`Invalid ${name} '${pattern}': ${getErrorMessage(error)}`);
    }
  };

  return {
    url,
    user: args.user ?? env.CLICKHOUSE_USER,
    password: args.password ?? env.CLICKHOUSE_PASSWORD,
    database: args.database ?? env.CLICKHOUSE_DATABASE ?? "default",
    ...(args.includePattern
      ? { includePattern: compilePattern(args.includePattern, "includePattern") }
      : {}),
    ...(args.excludePattern
      ? { excludePattern: compilePattern(args.excludePattern, "excludePattern") }
      : {}),
  };
}

export function filterExcludedObjects(
  objects: readonly IntrospectionObject[],
  includePattern?: RegExp,
  excludePattern?: RegExp,
): IntrospectionObject[] {
  return objects.filter((object) => {
    if (includePattern && !includePattern.test(object.name)) {
      return false;
    }

    if (excludePattern && excludePattern.test(object.name)) {
      return false;
    }

    return true;
  });
}

export function buildTypeScriptModuleResult(
  objects: readonly IntrospectionObject[],
  columns: readonly TypeScriptIntrospectionColumn[],
  headerOptions?: IntrospectionSchemaHeaderOptions,
): IntrospectionResult {
  if (objects.length === 0) {
    throw new Error("No tables or views were available to introspect.");
  }

  const orderedObjects = [...objects].sort(sortObjects);
  const columnsByObject = new Map<string, TypeScriptIntrospectionColumn[]>();
  for (const column of columns) {
    const existing = columnsByObject.get(column.objectName);
    if (existing) {
      existing.push(column);
    } else {
      columnsByObject.set(column.objectName, [column]);
    }
  }

  const failures: IntrospectionFailure[] = [];
  const tables: Array<{ name: string; columns: readonly TypeScriptIntrospectionColumn[] }> = [];
  const views: Array<{ name: string; columns: readonly TypeScriptIntrospectionColumn[] }> = [];

  for (const object of orderedObjects) {
    const objectColumns = columnsByObject.get(object.name) ?? [];
    if (objectColumns.length === 0) {
      failures.push({
        name: object.name,
        engine: object.engine,
        message: "Could not load column metadata for the introspected object.",
      });
      continue;
    }

    if (isTableLikeObject(object)) {
      tables.push({ name: object.name, columns: objectColumns });
    } else {
      views.push({ name: object.name, columns: objectColumns });
    }
  }

  if (tables.length + views.length === 0) {
    throw new Error(
      failures.length > 0
        ? formatIntrospectionFailureReport(
            failures,
            "Could not generate trusted TypeScript DB types for",
          )
        : "No supported tables or views were available to introspect.",
    );
  }

  return {
    source: tryFormatTypeScript(
      `${formatSchemaModuleHeader(headerOptions)}\n\n${generateTypeScriptSchemaModule(tables, views)}`,
    ),
    failures,
    summary: {
      generatedObjects: tables.length + views.length,
      generatedTables: tables.length,
      generatedViews: views.length,
      skippedObjects: failures.length,
    },
  };
}

export async function fetchDatabaseObjects(
  options: IntrospectionConnectionOptions,
  tablesOnly = false,
): Promise<IntrospectionObject[]> {
  const client = createClient({
    url: options.url,
    username: options.user,
    password: options.password,
    request_timeout: 30_000,
  });

  try {
    const result = await client.query({
      query: `
        SELECT
          name,
          engine
        FROM system.tables
        WHERE database = {database:String}
          AND engine NOT IN ('Dictionary', 'MaterializedView')
          ${tablesOnly ? "AND engine != 'View'" : ""}
      `,
      query_params: {
        database: options.database,
      },
      format: "JSONEachRow",
    });

    const rows = await result.json<SystemTableRow>();
    return rows.map((row) => ({
      name: row.name,
      engine: row.engine,
    }));
  } finally {
    await client.close();
  }
}

export async function fetchDatabaseColumns(
  options: IntrospectionConnectionOptions,
): Promise<TypeScriptIntrospectionColumn[]> {
  const client = createClient({
    url: options.url,
    username: options.user,
    password: options.password,
    request_timeout: 30_000,
  });

  try {
    const result = await client.query({
      query: `
        SELECT
          table,
          name,
          type,
          position
        FROM system.columns
        WHERE database = {database:String}
        ORDER BY table ASC, position ASC
      `,
      query_params: {
        database: options.database,
      },
      format: "JSONEachRow",
    });

    const rows = await result.json<SystemColumnRow>();
    return rows.map((row) => ({
      objectName: row.table,
      name: row.name,
      clickhouseType: row.type,
      position: row.position,
    }));
  } finally {
    await client.close();
  }
}

export async function writeSchemaModule(source: string, outPath: string): Promise<void> {
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, source, "utf8");
}

export async function introspectDatabase(args: IntrospectArgs): Promise<IntrospectionResult> {
  const options = resolveConnectionOptions(args);
  const allObjects = await fetchDatabaseObjects(options, args.tablesOnly);
  const filteredObjects = filterExcludedObjects(
    allObjects,
    options.includePattern,
    options.excludePattern,
  );
  const objects = args.tablesOnly ? filteredObjects.filter(isTableLikeObject) : filteredObjects;
  if (objects.length === 0) {
    throw new Error(
      args.tablesOnly
        ? `No table-like objects found in database '${options.database}'.`
        : `No tables or views found in database '${options.database}'.`,
    );
  }

  const columns = await fetchDatabaseColumns(options);
  return buildTypeScriptModuleResult(objects, columns, buildSchemaHeaderOptions(args, options));
}
